steps:
  - name: gcr.io/cloud_builders/docker
    id: Build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/go-nihao:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - gcr.io/$PROJECT_ID/go-nihao:$COMMIT_SHA
 
  - name: 'gcr.io/cloud-builders/git'
    id: Update CD
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
    cd .. && \
    git clone https://github.com/hughluo/go-nihao-cd && \
    cd go-nihao-cd && \
    echo "add $COMMIT_SHA" >> test.log && \
    # Configure Git to create commits with Cloud Build's service account
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git add test.log && \
    git commit -m "update from CI commit $COMMIT_SHA" && \
    git push origin master
