steps:
  - name: gcr.io/cloud_builders/docker
    id: Build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/go-nihao:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - gcr.io/$PROJECT_ID/go-nihao:$COMMIT_SHA
 
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clone env repository
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
    gcloud source repos clone go-nihao-cd && \
    cd go-nihao-cd && \
#     git checkout -b candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

  # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
  id: Update manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    echo "CI from $COMMIT_SHA" >> test.log

# This step pushes the manifest back to hello-cloudbuild-env
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd go-nihao-cd && \
    git add test.log && \
    git commit -m "ci integration test $COMMIT_SHA" && \
#     git push origin candidate
    git push master
